from streamlit_apps.apps.streamlit_app_research.presentation.components.styled_tabs_widget import styled_tabs_widget
from streamlit_apps.apps.streamlit_app_research.presentation.components.moving_average_select_widget import render_moving_average_select_widget
from streamlit_apps.apps.streamlit_app_research.presentation.components.information_table_widget import render_information_table_widget
from streamlit_apps.apps.streamlit_app_research.presentation.components.asset_monitor_table_widget import render_asset_monitor_table_widget